package com.myspace.moss;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MemorandumOfPresentation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "from")
	private java.lang.String from;
	@org.kie.api.definition.type.Label(value = "to")
	private java.lang.String to;
	@org.kie.api.definition.type.Label(value = "presentation")
	private java.lang.String presentation;
	@org.kie.api.definition.type.Label(value = "subject")
	private java.lang.String subject;
	@org.kie.api.definition.type.Label(value = "theRequired")
	private java.lang.String theRequired;

	public MemorandumOfPresentation() {
	}

	public java.lang.String getFrom() {
		return this.from;
	}

	public void setFrom(java.lang.String from) {
		this.from = from;
	}

	public java.lang.String getTo() {
		return this.to;
	}

	public void setTo(java.lang.String to) {
		this.to = to;
	}

	public java.lang.String getPresentation() {
		return this.presentation;
	}

	public void setPresentation(java.lang.String presentation) {
		this.presentation = presentation;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.lang.String getTheRequired() {
		return this.theRequired;
	}

	public void setTheRequired(java.lang.String theRequired) {
		this.theRequired = theRequired;
	}

	public MemorandumOfPresentation(java.lang.String from, java.lang.String to,
			java.lang.String presentation, java.lang.String subject,
			java.lang.String theRequired) {
		this.from = from;
		this.to = to;
		this.presentation = presentation;
		this.subject = subject;
		this.theRequired = theRequired;
	}

}