package com.myspace.moss;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ReviewObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Description(value = "approve or reject or data completion")
	@org.kie.api.definition.type.Label(value = "action")
	private java.lang.String action;
	@org.kie.api.definition.type.Label(value = "rejectionReason")
	private java.lang.String rejectionReason;
	@org.kie.api.definition.type.Label(value = "notes")
	private java.lang.String note;

	public ReviewObject() {
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getRejectionReason() {
		return this.rejectionReason;
	}

	public void setRejectionReason(java.lang.String rejectionReason) {
		this.rejectionReason = rejectionReason;
	}

	public java.lang.String getNote() {
		return this.note;
	}

	public void setNote(java.lang.String note) {
		this.note = note;
	}

	public ReviewObject(java.lang.String action,
			java.lang.String rejectionReason, java.lang.String note) {
		this.action = action;
		this.rejectionReason = rejectionReason;
		this.note = note;
	}

}